### ISSUE TITLE
create  sponsors list screen without design

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#178] opened 2022-09-05 03:55 UTC
**Idea Description**
create  sponsors list screen without design

issue devided apply design

**Reference images and links**
coming soon

**Comment by ho2ri2s** [comment] 2022-09-05 14:21
🙋‍♂️

**Comment by tomoya0x00** [comment] 2022-09-05 14:22
Thanks! Assigned 👍

**Comment by ho2ri2s** [comment] 2022-09-05 14:23
May I ask a question?
Do you mean implementing UI logic such as ViewModel other than UI in Compose?

**Comment by takahirom** [comment] 2022-09-05 14:24
👀

**Comment by ho2ri2s** [comment] 2022-09-05 14:39
I mistakenly thought it had a welcome-contribute tag 🙇 
I don't know what the problem is, but I would like to try!

**Comment by ho2ri2s** [comment] 2022-09-10 15:32
I'm just trying this Issue, and let me ask you a question 🙇 
What is the scope of what I need to create in this Issue?

1. create `feature-sponsor` module
2. definite navigation
3. think design myself and create screen with Compose(I think this is out of scope.)
4. add ViewModel, Repository, and so on with logic for display in Screen
6. fetch sponsors from specific endpoint and map to model from response model.
7. testing

Is the scope of this Issue all except 3? (Some may not be listed.)
If so, is there API documentation on what kind of Response is returned? 👀

**Comment by takahirom** [comment] 2022-09-11 05:40
@ho2ri2s 
Thank you for creating your breakdown of the issue.
Currently, we are creating the API. (by @RyuNen344 )

I think the response will be like this.


```kotlin
[
  {
    "id": "xxxxx"
    "sponsor_name": "DroidKaigi",
    "sponsor_logo": "https://hoge.png/",
    "plan": "GOLD",
    "link": "https://company.com/"
  },
...
]
```


> Is the scope of this Issue all except 3?

Yes, but it doesn't need to make a perfect screen. I think we can improve it.

**Comment by takahirom** [comment] 2022-09-11 08:14
If you have any questions let me know 🙏

**Comment by ho2ri2s** [comment] 2022-09-11 09:25
I will try to implementation by dividing PR.
Thank you for your answer 🚀

**Comment by RyuNen344** [comment] 2022-09-11 19:17
@ho2ri2s 

sorry for late

you can check it at `https://ssot-api-staging.an.r.appspot.com/events/droidkaigi2022/sponsor`

```json
"status": "OK", 
"sponsor": [
  {
    "sponsorName": "DroidKaigi",
    "sponsorLogo": "https://hoge.png/",
    "plan": "GOLD", // PLATINUM, GOLD, SUPPORTER
    "link": "https://company.com/"
  },
]
```

If you have any questions let me know 🙏

**Closed** 2022-09-19 06:25 UTC
Labels: high priority
